import Footer from "@/components/Footer";
import NavHeader from "@/components/NavHeader";
import Head from "next/head";
import React from "react";

export default function TermsAndConditions() {
  return (
    <>
      <Head>
        <title>PassengersClub | Terms and Conditions</title>
        <meta
          name="description"
          content="Experience the journey of a ridden ecosystem from its Adam. The train is what you make of it; however, the true journey begins when the eighth passenger awakes."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="px-5 lg:px-10">
        <NavHeader />
      </section>

      <div className="text-passengerWhite mt-20 lg:px-40 px-5">
        <h4 className=" text-[2rem] font-black italic uppercase">
          PASSENGERS CLUB TERMS & CONDITIONS
        </h4>
        <p className=" text-[0.85rem] my-5">
          This website is only an interface allowing participants to purchase
          Merchandise created by 4ColoredRings Labs. Users are entirely
          responsible for the safety and management of their own credit cards
          and validating all transactions and contracts generated by this
          website before approval. Furthermore, as the Passengers Club is
          strictly print on demand there is no ability to undo, reverse, restore
          or refund any transactions.
        </p>

        <p className=" text-[0.85rem] my-5">
          This website and its connected services are provided “as is” and “as
          available” without warranty of any kind. By using this website you are
          accepting sole responsibility for any and all transactions involving
          Passengers Club collectibles. Please read these Terms and Conditions
          of Use (“Terms”) carefully before using our Web Site and the Services.
          If you choose to continue to use or access this Web Site after having
          the opportunity to read these Terms, you recognise that 4ColoredRings
          Labs. has provided valuable consideration by offering this Web Site
          free of charge, and in exchange for that valuable consideration, you
          agree to the Terms hereof. If you do not agree to these Terms, please
          do not use the Web Site, and exit immediately.
        </p>

        <p className=" text-[0.85rem] my-5">
          We reserve the right to modify or amend the Terms from time to time
          without notice. Your continued use of our Web Site following the
          posting of changes to these terms will mean you accept those changes.
          Additional terms and conditions may apply to the purchase of products,
          such as shipping and return policies. By using this Web Site, you
          agree to such terms and conditions, as well as these Terms and our
          Privacy Policy (available here) (collectively, the “Agreement”).
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium">
          THESE TERMS INCLUDE AN AGREEMENT TO SUBMIT CLAIMS EXCLUSIVELY TO
          INDIVIDUAL (NON-CLASS) ARBITRATION. SEE BELOW.
        </h5>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          1. COPYRIGHT AND OWNERSHIP
        </h5>

        <p className=" text-[0.85rem] my-5">
          All of the content featured or displayed on the Web Site, including
          without limitation text, graphics, photographs, images, moving images,
          sound, and illustrations (“Content”), is owned by 4ColoredRings Labs,
          its licensors, vendors, agents, and/or its Content providers. All
          elements of the Web Site, including without limitation the general
          design and the Content, are protected by trade dress, copyright, moral
          rights, trademark, and other laws relating to intellectual property
          rights. The Services and the Web Site may only be used for the
          intended purpose for which such Web Site and Services are being made
          available. Except as may be otherwise indicated in specific documents
          within the Web Site, you are authorized to view, play, print, and
          download documents, audio, and video found on our Web Site for
          personal, informational, and noncommercial purposes only. You may not
          modify any of the materials and you may not copy, distribute,
          transmit, display, perform, reproduce, publish, license, create
          derivative works from, transfer or sell any information or work
          contained on the Web Site. Except as authorized under the copyright
          laws, you are responsible for obtaining permission before reusing any
          copyrighted material that is available on the Web Site. For purposes
          of these Terms, the use of any such material on any other website or
          networked computer environment is prohibited. You shall comply with
          all applicable domestic and international laws, statutes, ordinances,
          and regulations regarding your use of the Web Site and Services. The
          Web Site, its Content, and all related rights shall remain the
          exclusive property of 4ColoredRings Labs, or its licensors unless
          otherwise expressly agreed. You will not remove any copyright,
          trademark, or other proprietary notices from material found on these
          Web Site.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          2. PRODUCTS, CONTENT, AND SPECIFICATIONS
        </h5>

        <p className=" text-[0.85rem] my-5">
          All features, content, specifications, products, and prices of
          products and services described or depicted on this Web Site are
          subject to change at any time without notice. Certain weights,
          measures, and similar descriptions are approximate and are provided
          for convenience purposes only. We make all reasonable efforts to
          accurately display the attributes of our products, including the
          applicable colors; however, the actual color you see will depend on
          your computer system, and we cannot guarantee that your computer will
          accurately display such colors. The inclusion of any products or
          services on this Web Site at a particular time does not imply or
          warrant that these products or services will be available at any time.
          It is your responsibility to ascertain and obey all applicable local,
          state, federal, and international laws (including minimum age
          requirements) in regard to the possession, use, and sale of any item
          purchased from this Web Site. By placing an order, you represent that
          the products ordered will be used only in a lawful manner. All
          videocassettes, DVDs, and similar products sold are for private, home
          use (where no admission fee is charged), non-public performance and
          may not be duplicated.
        </p>

        <p className=" text-[0.85rem] my-5">
          Content on this Web Site may include images of people. Please be aware
          that we are not familiar with your individual physical characteristics
          and health. Before you begin an exercise program, you should get a
          medical checkup. It is important that you warm up and stretch before
          engaging in physical activity and that you use common sense while
          engaging in physical activity. If you experience any pain, feel weak,
          dizzy, or exhausted, or become short of breath, immediately stop your
          workout. When you engage in physical activity, you assume all inherent
          risks.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          3. SHIPPING LIMITATIONS
        </h5>

        <p className=" text-[0.85rem] my-5">
          When an order is placed, it will be shipped to an address designated
          by the purchaser as long as that shipping address is compliant with
          the shipping restrictions contained on this Web Site. All purchases
          from this Web Site are made pursuant to a shipment contract. As a
          result, the risk of loss and title for items purchased from this Web
          Site pass to you upon delivery of the items to the carrier.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          4. ACCURACY OF INFORMATION
        </h5>

        <p className=" text-[0.85rem] my-5">
          We attempt to ensure that information on this Web Site is complete,
          accurate, and current. Despite our efforts, the information on this
          Web Site may occasionally be inaccurate, incomplete, or out of date.we
          make no representation as to the completeness, accuracy, or currency
          of any information on this Web Site. For example, products included on
          this Web Site may be unavailable, may have different attributes than
          those listed, or may actually carry a different price than that stated
          on this Web Site. In addition, we may make changes in information
          about price and availability without notice. While it is our practice
          to confirm orders by email, the receipt of an email order confirmation
          does not constitute our acceptance of an order or our confirmation of
          an offer to sell a product or service. We reserve the right, without
          prior notice, to limit the order quantity on any product or service
          and/or to refuse service to any customer. We also may require
          verification of information prior to the acceptance and/or shipment of
          any order.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          5. THIRD-PARTY LINKS
        </h5>

        <p className=" text-[0.85rem] my-5">
          From time to time, this Web Site may contain links to websites that
          are not owned, operated, or controlled by 4ColoredRings Labs or its
          affiliates. All such links are provided solely as a convenience to
          you. If you use these links, you will leave this Web Site. Neither we
          nor any of our respective affiliates are responsible for any content,
          materials, or other information located on or accessible from any
          other website. Neither we nor any of our respective affiliates
          endorse, guarantee, or make any representations or warranties
          regarding any other web sites, or any content, materials, or other
          information located or accessible from any other web sites, or the
          results that you may obtain from using any other web sites. If you
          decide to access any other websites linked to or from this website,
          you do so entirely at your own risk.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          6. UNAUTHORIZED USE OF COMPUTER SYSTEM
        </h5>

        <p className=" text-[0.85rem] my-5">
          You are prohibited from posting or sending any unlawful, threatening,
          defamatory, libellous, obscene, pornographic, or profane material or
          any material that could constitute or encourage conduct that would be
          considered a criminal offense or give rise to civil liability, or
          otherwise violate any law. Such violations may subject the sender and
          his or her agents to civil and criminal penalties. You further
          understand and agree that sending unsolicited email advertisements to
          any user of the Web Site or the Web Site or through Voice computer
          systems is expressly prohibited by these Terms. Any such unauthorized
          use of our computer systems is a violation of these Terms and
          applicable “anti-spam” laws. In addition to any remedies that we may
          have at law or in equity, if we determine, in our sole discretion,
          that you have violated or are likely to violate the foregoing
          prohibitions, we may take any action we deem necessary to cure or
          prevent the violation, including without limitation, the immediate
          removal of the related materials from this Web Site. We will fully
          cooperate with any law enforcement authorities or court order or
          subpoena requesting or directing us to disclose the identity of anyone
          posting such materials.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          7. ACCOUNT SECURITY
        </h5>

        <p className=" text-[0.85rem] my-5">
          You are entirely responsible for the security and confidentiality of
          your password and account. Furthermore, you are entirely responsible
          for any and all activities that occur under your account. You agree to
          immediately notify us of any unauthorized use of your account or any
          other breach of security of which you become aware. You are
          responsible for taking precautions and providing security measures
          best suited for your situation and intended use of the Services and
          Web Site.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          8. USER-GENERATED CONTENT – INFORMATION CONTROL
        </h5>

        <p className=" text-[0.85rem] my-5">
          All opinions, remarks, comments, artwork, graphics, photographs,
          links, questions, suggestions, information, videos and other materials
          that you or other users of the Web Site post to the Web Site or
          transmit using the Web Site (“User-Generated Content”) do not
          represent the views of 4ColoredRings Labs or any individual associated
          with 4ColoredRings Labs, and we do not control this User Generated
          Content. In no event shall you represent or suggest, directly or
          indirectly, 4Colored RingsLabs endorsement of User Generated Content.
          4ColoredRings Labs does not vouch for the accuracy or credibility of
          any User Generated Content on our Web Site and does not take any
          responsibility or assume any liability for any actions you may take as
          a result of reading User Generated Content on our Web Site. Through
          your use of the Web Site and Services, you may be exposed to
          User-Generated Content that you may find offensive, objectionable,
          harmful, inaccurate, or deceptive. There may also be risks of dealing
          with underage persons, people acting under false pretense,
          international trade issues, and foreign nationals. By using our Web
          Site, you assume all associated risks.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          9. USER-GENERATED CONTENT – YOUR LICENSE TO US
        </h5>

        <p className=" text-[0.85rem] my-5">
          User-Generated Content remains the intellectual property of the
          individual user. By posting User Generated Content on our Web Site,
          you grant 4ColoredRings Labs a non-exclusive, perpetual, irrevocable,
          royalty-free, worldwide, fully sub-licensable right to use, reproduce,
          modify, adapt, publish, translate, create derivative works from,
          distribute, and display such User Generated Content throughout the
          world in any media, whether now known or hereafter discovered. In
          addition, you warrant that all so-called "moral rights" in those
          materials have been waived.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          10. FEES
        </h5>

        <p className=" text-[0.85rem] my-5">
          For all charges for any products and services sold on the Web
          Site,Passengers Club or 4ColoredRings Labs will bill your credit card
          or alternative payment method offered. Any seasonal surcharges will be
          included in your order's delivery total and are non-refundable. by
          purchasing a merchandise of 4ColoredRings Labs you agree to non-refund
          of any kind. In the event legal action is necessary to collect on
          balances due, you agree to reimburse 4ColoredRings Labs for all
          expenses incurred to recover sums due, including attorneys' fees and
          other legal expenses. You are responsible for the purchase of, and
          payment of charges for, all Internet access services, and
          telecommunications services needed for use of this Web Site.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          11. ACCESS AND INTERFERENCE
        </h5>

        <p className=" text-[0.85rem] my-5">
          You agree that you will not use any robot, spider, scraper, or other
          automated means to access the Web Site for any purpose without our
          express written permission. Additionally, you agree that you will not:
          (i) take any action that imposes or may impose in our sole discretion
          an unreasonable or disproportionately large load on our
          infrastructure; (ii) interfere or attempt to interfere with the proper
          working of the Web Site or any activities conducted on the Web Site;
          or (iii) bypass any measures we may use to prevent or restrict access
          to the Web Site.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          12. FORCE MAJEURE
        </h5>

        <p className=" text-[0.85rem] my-5">
          Neither 4ColoredRings Labs nor you shall be responsible for damages or
          for delays or failures in performance resulting from acts or
          occurrences beyond their reasonable control, including, without
          limitation: fire, lightning, explosion, power surge or failure, water,
          acts of God, war, revolution, civil commotion or acts of civil or
          military authorities or public enemies: any law, order, regulation,
          ordinance, or requirement of any government or legal body or any
          representative of any such government or legal body; or labor unrest,
          including without limitation, strikes, slowdowns, picketing, or
          boycotts; inability to secure raw materials, transportation
          facilities, fuel or energy shortages, or acts or omissions of other
          common carriers.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          13. PRIVACY
        </h5>

        <p className=" text-[0.85rem] my-5">
          Your use of our Web Site and Services is subject to our Privacy
          Policy. Please read our Privacy Policy linked to here.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          14. DISCLAIMER
        </h5>

        <p className=" text-[0.85rem] my-5">
          The information, materials, and services provided on or through this
          Web Site are provided “as is” without any warranties of any kind
          including warranties of merchantability, fitness for a particular
          purpose, or non-infringement of intellectual property. , neither
          4ColoredRings Labs nor any of its respective affiliates (i) warrant
          the accuracy or completeness of the information, materials, or
          services provided on or through the Web Site or (ii) makes any
          commitments or assumes any duty to update such information, materials
          or services.
        </p>

        <p className=" text-[0.85rem] my-5">
          Neither 4ColoredRings Labs, nor any of its respective affiliates,
          warrants that the functions contained in this Web Site will be
          uninterrupted or error-free, that defects will be corrected, or that
          the server that makes the content available will be free of viruses or
          other harmful components.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          15. LIMITATION OF LIABILITY
        </h5>

        <p className=" text-[0.85rem] my-5">
          Your use of the Web Site is at your own risk. You agree that our sole
          obligation to you is to provide the Web Site “as is.” neither
          4ColoredRings Labs nor any of its employees, officers, directors nor
          any of its agents or any other party involved in creating, producing,
          or delivering the Web Site shall be liable to you or to any third
          party for your use of, or the inability to use, the Web Site and its
          Content except in cases of (a) gross negligence, recklessness, or an
          act of knowing or intentional willful misconduct; or (b) a violation
          of a consumer protection statute in connection with the Web Site.
        </p>

        <p className=" text-[0.85rem] my-5">
          In no event will 4ColoredRingsLabs or any of their respective
          officers, directors, employees, shareholders, affiliates, agents,
          successors or assigns, nor any party involved in the creation,
          production, or transmission of this web site, be liable to you or
          anyone else for any indirect, special, punitive, incidental or
          consequential damages (including, without limitation, those resulting
          from lost profits, lost data or business interruption) arising out of
          the use, inability to use, or the results of the use of the Web Site,
          any web sites linked to this Web Site, and its Content, whether based
          on warranty, contract, tort or any other legal theory and whether or
          not advised of the possibility of such damages.
        </p>

        <p className=" text-[0.85rem] my-5">
          In the event of any problem with this Web Site or any Content, you
          agree that your sole remedy is to cease using this Web Site. In the
          event of any problem with the products or services that you have
          purchased on or through this Web Site, you agree that your sole
          remedy, if any, is from the manufacturer of such products or supplier
          of such services, in accordance with such manufacturer's or supplier's
          warranty, or to seek a return and refund for such product or services
          in accordance with the returns and refunds policies posted on this Web
          Site. in no event shall 4ColoredRings Labs’ total liability to you for
          all damages, losses, and causes of action whether in contract, tort
          (including, but not limited to, negligence), or otherwise exceed the
          greater of (a) fifty dollars ($50.00) or (b) the value of your
          purchase on the Web Site.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          16. INDEMNITY
        </h5>

        <p className=" text-[0.85rem] my-5">
          You agree to defend, indemnify and hold 4ColoredRings Labs and any
          affiliated company or individual harmless from any and all
          liabilities, costs, and expenses, including reasonable attorneys'
          fees, related to any violation of these Terms by you or your
          authorized users, or in connection with the use of the Web Site or the
          Internet or your purchases or the placement or transmission of any
          message or information on this Web Site by you or your authorized
          users or your violation of any law or the rights of a third party.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          17. RELEASE
        </h5>

        <p className=" text-[0.85rem] my-5">
          In the event that you have a dispute with one or more other users of
          the Web Site, you release 4ColoredRings Labs (and its officers,
          directors, agents, subsidiaries, joint ventures, and employees) from
          claims, demands, and damages (actual and consequential) of every kind
          and nature, known and unknown, suspected and unsuspected, disclosed
          and undisclosed, arising out of or in any way connected with such
          disputes.
        </p>

        <h5 className="text-passengerWhite text-[1rem] font-medium my-5">
          18. TERMINATION
        </h5>

        <p className=" text-[0.85rem] my-5">
          You or we may suspend or terminate your account or your use of this
          Web Site at any time, for any reason, or for no reason. You are
          personally liable for any orders placed or charges incurred through
          your account prior to termination. We may also block your access to
          our Web Site in the event that (a) you breach these Terms of Service;
          (b) we are unable to verify or authenticate any information you
          provide to us; or (c) we believe that your actions may cause financial
          loss or legal liability for you, our users or us.
        </p>
      </div>
    </>
  );
}
