import Footer from "@/components/Footer";
import NavHeader from "@/components/NavHeader";
import Head from "next/head";
import React from "react";

export default function TermsAndConditions() {
  return (
    <>
      <Head>
        <title>PassengersClub</title>
        <meta
          name="description"
          content="Experience the journey of a ridden ecosystem from its Adam. The train is what you make of it; however, the true journey begins when the eighth passenger awakes."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="px-5 lg:px-10">
        <NavHeader />
      </section>

      <div className="text-passengerWhite mt-20">
        <h4 className="lg:px-20 px-5 text-[2rem] font-black italic uppercase">
          PASSENGERS CLUB TERMS & CONDITIONS
        </h4>
        <p className="px-5 lg:px-20 text-[0.85rem]"></p>
        Passengers Club is a collection of digital artworks (NFTs) running on
        the Ethereum network. This website is only an interface allowing
        participants to purchase digital collectibles. Users are entirely
        responsible for the safety and management of their own private Ethereum
        wallets and validating all transactions and contracts generated by this
        website before approval. Furthermore, as the Passengers Club smart
        contract runs on the Ethereum network, there is no ability to undo,
        reverse, or restore any transactions. This website and its connected
        services are provided "as is" and "as available" without warranty of any
        kind. By using this website, you are accepting sole responsibility for
        any and all transactions involving Passengers Club digital collectibles.
        This website is only an interface allowing participants to purchase
        merchandise created by 4COLOREDRINGS LABS LTD. Users are entirely
        responsible for the safety and management of their own credit cards and
        validating all transactions and contracts generated by this website
        before approval. Furthermore, as the Passengers Club is strictly
        print-on-demand, there is no ability to undo, reverse, restore, or
        refund any transactions. This website and its connected services are
        provided "as is" and "as available" without warranty of any kind. By
        using this website, you are accepting sole responsibility for any and
        all transactions involving Passengers Club collectibles. Please read
        these Terms and Conditions of Use ("Terms") carefully before using our
        Web site and the services. If you choose to continue to use or access
        this web site after having had the opportunity to read these terms, you
        recognize that 4 Colored Rings Labs. has provided valuable consideration
        by offering this web site free of charge, and in exchange for that
        valuable consideration, you agree to the terms hereof. If you do not
        agree to these terms, please do not use the Web site and exit
        immediately. We reserve the right to modify or amend the Terms from time
        to time without notice. Your continued use of our Web site following the
        posting of changes to these terms will mean you accept those changes.
        Additional terms and conditions may apply to the purchase of products,
        such as shipping and return policies. By using this Web site, you agree
        to such terms and conditions, as well as these terms and our privacy
        policy (available here) (collectively, the "Agreement"). THESE TERMS
        INCLUDE AN AGREEMENT TO SUBMIT CLAIMS EXCLUSIVELY TO INDIVIDUAL
        (NON-CLASS) ARBITRATION. SEE BELOW. 1. COPYRIGHT AND OWNERSHIP All of
        the content featured or displayed on the Web site, including without
        limitation text, graphics, photographs, images, moving images, sound,
        and illustrations ("Content"), is owned by 4COLOREDRINGS LABS LTD, its
        licensors, vendors, agents, and/or its Content providers. All elements
        of the Web site, including without limitation the general design and the
        content, are protected by trade dress, copyright, moral rights,
        trademarks, and other laws relating to intellectual property rights. The
        services and the web site may only be used for the intended purposes for
        which such a web site and services are being made available. Except as
        may be otherwise indicated in specific documents within the Web site,
        you are authorized to view, play, print, and download documents, audio,
        and video found on our Web site for personal, informational, and
        noncommercial purposes only. You may not modify any of the materials,
        and you may not copy, distribute, transmit, display, perform, reproduce,
        publish, license, create derivative works from, transfer, or sell any
        information or work contained on the Web site. Except as authorized
        under the copyright laws, you are responsible for obtaining permission
        before reusing any copyrighted material that is available on the Web
        site. For purposes of these Terms, the use of any such material on any
        other website or networked computer environment is prohibited. You shall
        comply with all applicable domestic and international laws, statutes,
        ordinances, and regulations regarding your use of the Web site and
        services. The Web site, its content, and all related rights shall remain
        the exclusive property of 4COLOREDRINGS LABS LTD. or its licensors
        unless otherwise expressly agreed. You will not remove any copyright,
        trademark, or other proprietary notices from material found on these Web
        sites. 1.1 OWNERSHIP You own the NFT. Each passenger is an NFT on the
        Ethereum blockchain. When you purchase an NFT, you own the underlying
        passenger, the art, completely. Ownership of the NFT is mediated
        entirely by the smart contract and the Ethereum network; at no point may
        we seize, freeze, or otherwise modify the ownership of any passenger. B.
        Personal Use Subject to your continued compliance with these Terms,
        4COLOREDRINGS LABS LTDoffers you a worldwide, royalty-free license to
        use, copy, and display the purchased art, along with any extensions that
        you choose to create or use, solely for the following purposes: (i) for
        your own personal, non-commercial use; (ii) as part of a marketplace
        that permits the purchase and sale of your Passenger / NFT, provided
        that the marketplace cryptographically verifies each Passenger owner’s
        rights to display the Art for their Passenger to ensure that only the
        actual owner can display the Art; or (iii) as part of a third party
        website or application that permits the inclusion, involvement, or
        participation of your Passenger, provided that the website/application
        cryptographically verifies each Passenger owner’s rights to display the
        Art for their Passenger to ensure that only the actual owner can display
        the Art, and provided that the Art is no longer visible once the owner
        of the Passenger leaves the website/application. C. Commercial Use
        Subject to your continued compliance with these Terms, 4COLOREDRINGS
        LABS LTD offers you an unlimited, worldwide license to use, copy, and
        display the purchased art for the purpose of creating derivative works
        based upon the art ("Commercial Use"). Examples of such commercial use
        would, e.g., be the use of the art to produce and sell merchandise
        products (T-shirts, etc.) displaying copies of the art. For the sake of
        clarity, nothing in this Section will be deemed to restrict you from:
        (i) owning or operating a marketplace that permits the use and sale of
        passengers generally, provided that the marketplace cryptographically
        verifies each passenger owner’s rights to display the art for their
        passenger to ensure that only the actual owner can display the art; (ii)
        owning or operating a third party website or application that permits
        the inclusion, involvement, or participation of passengers generally,
        provided that the third party website or application cryptographically
        verifies each passenger owner’s rights to display the art for their
        passenger to ensure that only the actual owner can display the art; or
        (ii) earning revenue from any of the foregoing D. Other than the rights
        to the art, nothing herein gives you any rights to any other trademarks
        or other intellectual property rights belonging to 4COLOREDRINGS LABS
        LTD including, without limitation, Passengers Club and the associated
        logos. All of these rights are expressly reserved in the name of 4
        Colored Rings Labs, Ltd. E. Feedback. You may choose to submit comments,
        bug reports, ideas, or other feedback about the site, including without
        limitation about how to improve the site (collectively, "feedback"). By
        submitting any feedback, you agree that we are free to use such feedback
        in any way we choose without additional compensation to you, and you
        hereby grant us a perpetual, irrevocable, nonexclusive, worldwide
        license to incorporate and use the feedback for any purpose. 2.
        PRODUCTS, CONTENT, AND SPECIFICATIONS All features, content,
        specifications, products, and prices of products and services described
        or depicted on this Web site are subject to change at any time without
        notice. Certain weights, measures, and similar descriptions are
        approximate and are provided for convenience purposes only. We make all
        reasonable efforts to accurately display the attributes of our products,
        including the applicable colors; however, the actual color you see will
        depend on your computer system, and we cannot guarantee that your
        computer will accurately display such colors. The inclusion of any
        products or services on this Web site at a particular time does not
        imply or warrant that these products or services will be available at
        any time. It is your responsibility to ascertain and obey all applicable
        local, state, federal, and international laws (including minimum age
        requirements) in regard to the possession, use, and sale of any item
        purchased from this Web site. By placing an order, you represent that
        the products ordered will be used only in a lawful manner. All
        videocassettes, DVDs, and similar products sold are for private, home
        use (where no admission fee is charged), non-public performance, and may
        not be duplicated. Content on this Web site may include images of
        people. Please be aware that we are not familiar with your individual
        physical characteristics and health. Before you begin an exercise
        program, you should get a medical checkup. It is important that you warm
        up and stretch before engaging in physical activity and that you use
        common sense while engaging in physical activity. If you experience any
        pain, feel weak, dizzy, exhausted, or become short of breath,
        immediately stop your workout. When you engage in physical activity, you
        assume all its inherent risks. 3. SHIPPING LIMITATIONS When an order is
        placed, it will be shipped to an address designated by the purchaser, as
        long as that shipping address is compliant with the shipping
        restrictions contained on this Web site. All purchases from this Web
        site are made pursuant to a shipment contract. As a result, the risk of
        loss and title to items purchased from this Web site pass to you upon
        delivery of the items to the carrier. 4. ACCURACY OF INFORMATION We
        attempt to ensure that the information on this Web site is complete,
        accurate, and current. Despite our efforts, the information on this Web
        site may occasionally be inaccurate, incomplete, or out of date. We make
        no representations as to the completeness, accuracy, or currency of any
        information on this Web site. For example, products included on this Web
        site may be unavailable, have different attributes than those listed, or
        actually carry a different price than that stated on the site. In
        addition, we may make changes in information about price and
        availability without notice. While it is our practice to confirm orders
        by email, the receipt of an email order confirmation does not constitute
        our acceptance of an order or our confirmation of an offer to sell a
        product or service. We reserve the right, without prior notice, to limit
        the order quantity of any product or service and/or refuse service to
        any customer. We also may require verification of information prior to
        the acceptance and/or shipment of any order. 5. THIRD-PARTY LINKS From
        time to time, this Web site may contain links to other websites that are
        not owned, operated, or controlled by 4COLOREDRINGS LABS LTD or its
        affiliates. All such links are provided solely as a convenience to you.
        If you use these links, you will leave this Web site. Neither we nor any
        of our respective affiliates are responsible for any content, materials,
        or other information located on or accessible from any other website.
        Neither we nor any of our respective affiliates endorse, guarantee, or
        make any representations or warranties regarding any other web sites,
        any content, materials, or other information located on or accessible
        from any other web sites, or the results that you may obtain from using
        any other web sites. If you decide to access any other websites linked
        to or from this website, you do so entirely at your own risk. 6.
        UNAUTHORIZED USE OF A COMPUTER SYSTEM You are prohibited from posting or
        sending any unlawful, threatening, defamatory, libellous, obscene,
        pornographic, or profane material or any material that could constitute
        or encourage conduct that would be considered a criminal offense or give
        rise to civil liability or otherwise violate any law. Such violations
        may subject the sender and his or her agents to civil and criminal
        penalties. You further understand and agree that sending unsolicited
        email advertisements to any user of the Web site or through voice
        computer systems is expressly prohibited by these Terms. Any such
        unauthorized use of our computer systems is a violation of these terms
        and applicable "anti-spam" laws. In addition to any remedies that we may
        have at law or in equity, if we determine, in our sole discretion, that
        you have violated or are likely to violate the foregoing prohibitions,
        we may take any action we deem necessary to cure or prevent the
        violation, including, without limitation, the immediate removal of the
        related materials from this Web site. We will fully cooperate with any
        law enforcement authorities or court order or subpoena requesting or
        directing us to disclose the identity of anyone posting such materials.
        7. ACCOUNT SECURITY You are entirely responsible for the security and
        confidentiality of your password and account. Furthermore, you are
        entirely responsible for any and all activities that occur under your
        account. You agree to immediately notify us of any unauthorized use of
        your account or any other breach of security of which you become aware.
        You are responsible for taking precautions and providing security
        measures best suited for your situation and intended use of the services
        and web site. 8. USER-GENERATED CONTENT—INFORMATION CONTROL All
        opinions, remarks, comments, artwork, graphics, photographs, links,
        questions, suggestions, information, videos, and other materials that
        you or other users of the Web site post to the Web site or transmit
        using the Web site ("User-Generated Content") do not represent the views
        of 4COLOREDRINGS LABS LTD or any individual associated with
        4COLOREDRINGS LABS LTD, and we do not control this User Generated
        Content. In no event shall you represent or suggest, directly or
        indirectly, 4Colored Colored Rings Labs' endorsement of user-generated
        content. 4COLOREDRINGS LABS LTD does not vouch for the accuracy or
        credibility of any User Generated Content on our Web Site and does not
        take any responsibility or assume any liability for any actions you may
        take as a result of reading User Generated Content on our Web Site.
        Through your use of the Web site and services, you may be exposed to
        user-generated content that you may find offensive, objectionable,
        harmful, inaccurate, or deceptive. There may also be risks in dealing
        with underage persons, people acting under false pretenses,
        international trade issues, and foreign nationals. By using our Web
        site, you assume all associated risks. 9. USER-GENERATED CONTENT—YOUR
        LICENSE TO US User-generated content remains the intellectual property
        of the individual user. By posting User Generated Content on our Web
        Site, you grant 4COLOREDRINGS LABS LTD a non-exclusive, perpetual,
        irrevocable, royalty-free, worldwide, fully sub-licensable right to use,
        reproduce, modify, adapt, publish, translate, create derivative works
        from, distribute, and display such User Generated Content throughout the
        world in any media, whether now known or hereafter discovered. In
        addition, you warrant that all so-called "moral rights" in those
        materials have been waived. 10. FEES For all charges for any products
        and services sold on the Web site,Passengers Club or 4COLOREDRINGS LABS
        LTD will bill your credit card or alternative payment method offered.
        Any seasonal surcharges will be included in your order's delivery total
        and are non-refundable. By purchasing merchandise of 4COLOREDRINGS LABS
        LTD you agree to no refunds of any kind. In the event legal action is
        necessary to collect on balances due, you agree to reimburse
        4COLOREDRINGS LABS LTD for all expenses incurred to recover sums due,
        including attorneys' fees and other legal expenses. You are responsible
        for the purchase of, and payment of charges for, all Internet access
        services, and telecommunications services needed for use of this Web
        site. 11. ACCESS AND INTERFERENCE You agree that you will not use any
        robot, spider, scraper, or other automated means to access the Web site
        for any purpose without our express written permission. Additionally,
        you agree that you will not: (i) take any action that imposes or may
        impose, in our sole discretion, an unreasonable or disproportionately
        large load on our infrastructure; (ii) interfere or attempt to interfere
        with the proper working of the Web Site or any activities conducted on
        the Web Site; or (iii) bypass any measures we may use to prevent or
        restrict access to the Web Site. 12. FORCE MAJURE Neither 4COLOREDRINGS
        LABS LTDnor you shall be responsible for damages or for delays or
        failures in performance resulting from acts or occurrences beyond their
        reasonable control, including, without limitation: fire, lightning,
        explosion, power surge or failure, water, acts of God, war, revolution,
        civil commotion, or acts of civil or military authorities or public
        enemies: any law, order, regulation, ordinance, or requirement of any
        government or legal body or any representative of any such government or
        legal body; or labor unrest, including without limitation, strikes,
        slowdowns, picketing, or boycotts; inability to secure raw materials,
        transportation facilities, fuel or energy shortages, or acts or
        omissions of other common carriers. 13. PRIVACY Your use of our Web site
        and services is subject to our Privacy Policy. Please read our privacy
        policy linked here. 14. DISCLAIMER The information, materials, and
        services provided on or through this Web site are provided "as is" and
        without any warranties of any kind, including warranties of
        merchantability, fitness for a particular purpose, or non-infringement
        of intellectual property. Neither 4 Colored Rings Ltd nor any of its
        respective affiliates (i) warrant the accuracy or completeness of the
        information, materials, or services provided on or through the Web Site
        or (ii) make any commitments or assume any duty to update such
        information, materials, or services. Neither 4 Colored Rings Ltd. nor
        any of its respective affiliates warrant that the functions contained in
        this Web site will be uninterrupted or error-free, that defects will be
        corrected, or that the server that makes the content available will be
        free of viruses or other harmful components. 15. LIMITATION OF LIABILITY
        Your use of the Web site is at your own risk. You agree that our sole
        obligation to you is to provide the Web site "as is." Neither
        4COLOREDRINGS LABS LTD nor any of its employees, officers, directors,
        nor any of its agents or any other party involved in creating,
        producing, or delivering the Web Site shall be liable to you or to any
        third party for your use of, or the inability to use, the Web Site and
        its Content, except in cases of (a) gross negligence, recklessness, or
        an act of knowing or intentional willful misconduct; or (b) a violation
        of a consumer protection statute in connection with the Web Site. In no
        event will 4COLOREDRINGS LABS LTD. or any of their respective officers,
        directors, employees, shareholders, affiliates, agents, successors, or
        assigns, nor any party involved in the creation, production, or
        transmission of this web site be liable to you or anyone else for any
        indirect, special, punitive, incidental, or consequential damages
        (including, without limitation, those resulting from lost profits, lost
        data, or business interruption) arising out of the use, inability to
        use, or the results of the use of the Web Site, any web sites linked to
        this site, or its Content, whether based on warranty, contract, tort, or
        any other legal theory, whether or not advised of the possibility of
        such damages. In the event of any problem with this Web site or any
        content, you agree that your sole remedy is to cease using this Web
        site. In the event of any problem with the products or services that you
        have purchased on or through this Web site, you agree that your sole
        remedy, if any, is from the manufacturer of such products or supplier of
        such services, in accordance with such manufacturer's or supplier's
        warranty, or to seek a return and refund for such product or services in
        accordance with the returns and refunds policies posted on this Web
        site. In no event shall 4COLOREDRINGS LABS LTD's total liability to you
        for all damages, losses, and causes of action, whether in contract, tort
        (including, but not limited to, negligence), or otherwise, exceed the
        greater of (a) fifty dollars ($50.00) or (b) the value of your purchase
        on the Web site. 17. INDEMNITY You agree to defend, indemnify and hold
        4COLOREDRINGS LABS LTDand any affiliated company or individual harmless
        from any and all liabilities, costs, and expenses, including reasonable
        attorneys' fees, related to any violation of these Terms by you or your
        authorized users, or in connection with the use of the Web Site or the
        Internet or your purchases or the placement or transmission of any
        message or information on this Web Site by you or your authorized users
        or your violation of any law or the rights of a third party. 18. RELEASE
        In the event that you have a dispute with one or more other users of the
        Web site, you release 4COLOREDRINGS LABS LTD. and its officers,
        directors, agents, subsidiaries, joint ventures, and employees from
        claims, demands, and damages (actual and consequential) of every kind
        and nature, known and unknown, suspected and unsuspected, disclosed and
        undisclosed, arising out of or in any way connected with such disputes.
        19. TERMINATION You or we may suspend or terminate your account or your
        use of this Web site at any time, for any reason, or for no reason. You
        are personally liable for any orders placed or charges incurred through
        your account prior to termination. We may also block your access to our
        Web site in the event that (a) you breach these Terms of Service, (b) we
        are unable to verify or authenticate any information you provide to us,
        or (c) we believe that your actions may cause financial loss or legal
        liability for you, our users, or us. 20. WEB SITE DISPUTES "Web Site
        Disputes" include: (a) any claim you may have against 4 Colored Rings
        Ltd in connection with the Site; (b) any claim 4COLOREDRINGS LABS LTD
        may have against you in connection with the Site; and (c) any action to
        enforce the Terms and Conditions or to object to the Terms and
        Conditions. All other disputes are "non-web site disputes." Any claim
        arising from your purchase of an 4 Colored Rings Ltd product or service
        is a "non-website" dispute. Any claim arising from the content of any
        offer or advertisement on the site is a "non-website dispute. 21. WEB
        SITE DISPUTE RESOLUTION—ARBITRATION, JURY TRIAL WAIVER, AND CLASS ACTION
        WAIVER Neither you nor we will be able to sue in court in connection
        with a web site dispute. All Web site disputes must be resolved through
        individual (non-class) arbitration. You indicate your acceptance of
        these Terms and Conditions, including this agreement to arbitrate, by
        continuing to use the site after having had the opportunity to review
        these Terms and Conditions. You agree that you will not file a class
        action against 4COLOREDRINGS LABS LTD and its affiliated companies, or
        participate in a class action against 4COLOREDRINGS LABS LTD and its
        affiliated companies, in any Web site dispute. You agree that you will
        not file or seek class arbitration or participate in a class arbitration
        against 4 Colored Rings Ltd. and its affiliated companies in any Web
        site dispute. 22. DELUXE SALES These membership terms and conditions
        ("Membership Terms") govern your participation in the 4COLOREDRINGS LABS
        LTD. online Deluxe sale (" Deluxe Sale"). Please read them carefully
        before participating. By participating in a Deluxe Sale, you agree to be
        bound by these Membership Terms and the decisions of 4 Colored Rings
        Labs LLC. These Membership Terms apply in addition to the other terms
        and conditions that apply to your use of www.4coloredringslabs.com (the
        "Web Site") and the 4COLOREDRINGS LABS LTDmobile application (the "App,"
        and together with the Web Site, the "Platform"). If there is a conflict
        between the general terms and conditions for the platform and these
        membership terms, then these membership terms will control. 23.1
        INTRODUCTION The Deluxe Sale is an opportunity for customers to purchase
        a limited edition Passengers Club product ("Membership Product") through
        the platform or solely through the app. 23.2 ELIGIBILITY The Deluxe Sale
        is open only to legal buyers of legal age. 23.3 SALE PERIOD The
        Membership and Deluxe Sale begins and ends during the period described
        in the Platform (the "Sale Period"). 23.4 HOW TO PARTICIPATE In order to
        participate through the app, you must have a mobile phone that uses the
        iOS or Android operating system and has the ability to receive text
        messages. You also must have location services and in-app messaging
        enabled on your mobile phone. If you are under 18 or otherwise under the
        legal age of majority in the jurisdiction in which the entrant resides
        (a "Minor"), you must obtain your parent’s or legal guardian’s
        permission to participate, and they must agree to these Membership Terms
        prior to your participation. To participate, create a Passengers Club
        account. Once you have an account, during the sale period, you must
        enter the requested information to complete your participation. 23.5
        Participation Rules There may be a limit of one membership product per
        person during the sale period. This will be communicated to you through
        the platform. All entries must be submitted and received before the
        conclusion of the sales period. Normal time rates and data charges, if
        any, charged by your internet or mobile service provider will apply. All
        entries are subject to verification at any time. Proof of submission
        does not constitute proof of entry. 23.6 SELECTION OF PURCHASERS After
        the end of the sales period, participants will be selected at random or
        on a first-come, first served basis, to purchase the membership product
        ("Purchaser"). If participants are selected at random, then some
        advantage is given to higher-tier Passengers Club members. Being a
        Passengers Club member, even in the higher tiers, does not guarantee
        that you will be selected to be a purchaser. You will be notified of the
        selection method through the platform. 23.7 PRODUCT PURCHASE AND
        DELIVERY Ensure to put the right address, as we will not be held
        responsible if you don't. 23.8 PRODUCT AVAILABILITY We are offering a
        limited number of membership products for purchase through the Deluxe
        Sale. This offer is good while supplies last and may be limited to one
        membership product per participant and account during the Deluxe Sale.
        23.9 GENERAL RULES 4COLOREDRINGS LABS LTD. reserves the right to modify
        these membership terms and to cancel, modify, or suspend the Deluxe Sale
        at any time. 4COLOREDRINGS LABS LTD has the right, in its sole
        discretion, to disqualify or prohibit from participating in the Deluxe
        Sale any individual who 4COLOREDRINGS LABS LTD believes: (i) has
        tampered with the entry process or undermined the legitimate operation
        of the Deluxe Sale in any manner; (ii) has engaged in conduct that
        annoys, abuses, threatens, or harasses any other participant or any
        representative of 4 Colored Rings Labs LLC; or (ii) has attempted or
        intends to attempt any of the foregoing. The use of agents or automated
        devices, programs, or methods to submit entries is prohibited, and
        4COLOREDRINGS LABS LTD has the right, in its sole discretion, to
        disqualify any participant that it believes may have been submitted an
        entry using such an agent or automated device, program, or method. 23.12
        TAXES If we select participants at random, we may not always be able to
        compute the exact amount of tax at the time you enter the membership
        sale. In these situations, taxes that appear when you enter the
        membership or Deluxe Sale may be estimated. The actual taxes charged to
        your payment method will be calculated based on the applicable state and
        local tax rates if and when you are selected to purchase the Deluxe,
        Regular, or Membership Product and will be reflected on the receipt
        emailed to you at that time. 24. ENTIRE AGREEMENT The Agreement
        constitutes the entire agreement between the user and 4COLOREDRINGS LABS
        LTD and supersedes any prior understandings or agreements (written or
        oral). If you do not understand any of the foregoing terms, please leave
        this site. 25. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING
        INFORMATION AND DEALING ONLINE OVER THE INTERNET, AND AGREE THAT WE HAVE
        NO LIABILITY OR RESPONSIBILITY FOR ANY BREACH OF SECURITY UNLESS IT IS
        DUE TO OUR WILLFUL MISCONDUCT. 26. Other than the rights to the art,
        nothing herein gives you any rights to any other trademarks or other
        intellectual property rights belonging to 4COLOREDRINGS LABS LTD,
        including, without limitation, Passengers Club and the associated logos.
        All of these rights are expressly reserved in the name of 4COLOREDRINGS
        LABS LTD. 27. CHILDREN Our site is not intended for children. You must
        be at least 18 years old to access this site or purchase merchandise. If
        you are under 18 years old, you are not permitted to use this site for
        any reason. By accessing the site, you represent and warrant that you
        are at least 18 years of age
      </div>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
